CREATE TABLE "GCG_6491_Quote_Brkdn" (
 "BIRUNID" BIGINT,
 "ROUTER" CHAR(20),
 "QUANTITY" DOUBLE,
 "DESCRIPTION" CHAR(50),
 "UNIT_PRICE" DOUBLE,
 "UNIT_COST" DOUBLE,
 "GROSS_PROFIT" DOUBLE );
 
CREATE INDEX "GCG_6491_Quote_Brkdn" ON "GCG_6491_Quote_Brkdn" ( "BIRUNID", "ROUTER" );